create table if not exists public.account_invitations (
  id bigint generated by default as identity primary key,
  account_id integer not null references public.admins(id) on delete cascade,
  token_hash bytea not null unique
    check (octet_length(token_hash) = 32),
  expires_at timestamptz not null,
  used_at timestamptz,
  created_by integer references public.admins(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.account_invitations enable row level security;

create index if not exists idx_account_invitations_pending_account
on public.account_invitations (account_id, created_at desc)
where used_at is null;

create index if not exists idx_account_invitations_pending_expiry
on public.account_invitations (expires_at)
where used_at is null;

create index if not exists idx_admins_hosted_created_at
on public.admins (created_at desc)
where auth_source = 'hosted';
