create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  account_id integer not null references public.admins(id) on delete cascade,
  provider text not null default 'stripe'
    check (provider = 'stripe'),
  provider_customer_id text not null,
  provider_subscription_id text,
  price_id text,
  status text not null default 'checkout_pending',
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  last_event_created_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, provider),
  unique (provider_customer_id),
  unique (provider_subscription_id)
);

create table if not exists public.billing_events (
  provider_event_id text primary key,
  event_type text not null,
  event_created_at timestamptz,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  outcome text not null default 'received'
    check (outcome in ('received', 'processed', 'ignored')),
  payload_digest text not null
);

alter table public.subscriptions enable row level security;
alter table public.billing_events enable row level security;

create index if not exists idx_subscriptions_status
on public.subscriptions (status, current_period_end);

create index if not exists idx_billing_events_received_at
on public.billing_events (received_at desc);
